### ISSUE TITLE
Weigths

### ISSUE THREAD

**Issue by lblb23** [hjweide/convnet-for-geometric-matching#1]
Hello! Very cool implementation!

Can you public pls weights of networks? If it's possible of course :)

**Comment by hjweide** [comment]
Thanks, I hope it's useful to you.  Feel free to submit a pull request if you implement any of the missing features.  I've just added links to the learned weights in the README, you can download them [here](https://drive.google.com/file/d/0B8qxCmGEZj4oejgwcERUSjBtbkk/view?usp=sharing).  Let me know if that doesn't work for you.

**Comment by lblb23** [comment]
Thank you! 

Unfortunately, I got an error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-d63985bd8154> in <module>()
      7 with open(weightsfile, 'rb') as f:
      8     param_values = pickle.load(f, encoding='latin1')
----> 9 set_all_param_values(layers['trans'], param_values)
     10 
     11 pretrainfile = join('weights', 'vgg16.pkl')

~/.local/lib/python3.5/site-packages/lasagne/layers/helper.py in set_all_param_values(layer, values, **tags)
    514     if len(params) != len(values):
    515         raise ValueError("mismatch: got %d values to set %d parameters" %
--> 516                          (len(values), len(params)))
    517 
    518     for p, v in zip(params, values):

ValueError: mismatch: got 52 values to set 32 parameter
```

**Comment by hjweide** [comment]
Ah, that was my mistake.  If you take a look at commit 1f2b2cba878b4242005e9ff20dcbd2efcc7318d7, you'll notice I changed the architecture to share parameters for the feature extraction network.  Even though these parameters aren't learned, sharing the parameters means that we can get away with a smaller memory footprint.  Basically, the weights file I uploaded was for the old architecture, which is why there are 20 more parameters (those from the feature extraction layers).

So I suggest you do one of the following three things:

1. rollback the commit I linked above and use the uploaded weights with the old architecture,
2. use the most recent commit and train your own model, or
3. if you're unable to train your own model, let me know and I'll train one and upload the new weights.  That should take about 24 hours.

**Comment by lblb23** [comment]
Ok, ty for answer. Then I will try to use the old architecture)

**Comment by hjweide** [comment]
In the meantime I'm going to train another model using the new architecture.  I'll upload the weights and send you a link when it's done.

**Comment by lblb23** [comment]
Thank you!

**Comment by hjweide** [comment]
I trained the model for about 800 epochs.  You can download the new weights [here](https://drive.google.com/file/d/0B8qxCmGEZj4obXFEN1paX3lBRmM/view?usp=sharing).  Let me know if that works for you.

**Comment by hjweide** [comment]
Closing, feel free to reopen if you run into more issues.
